"use server";
import { revalidatePath } from "next/cache";
import { requireAdmin } from "@/lib/rbac";
import { products } from "@/lib/mongodb";
import { adminProductSchema } from "@/lib/schemas/admin";
function value(formData: FormData) { return { ...Object.fromEntries(formData), featured: formData.get("featured") === "on", published: formData.get("published") !== "off", installable: formData.get("installable") === "on", badge: String(formData.get("badge") || "") }; }
export async function createProductAction(formData: FormData) { await requireAdmin(); const parsed = adminProductSchema.safeParse(value(formData)); if (!parsed.success) return { error: "Please check product fields.", fieldErrors: parsed.error.flatten().fieldErrors }; const data = { ...parsed.data, id: parsed.data.slug, variants: [], features: [], rating: 0, reviewCount: 0, inStock: parsed.data.stockQty > 0, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }; await (await products()).insertOne(data); revalidatePath("/admin/products"); revalidatePath("/shop"); return { success: true, id: data.id }; }
export async function updateProductAction(formData: FormData) { await requireAdmin(); const parsed = adminProductSchema.safeParse(value(formData)); if (!parsed.success || !parsed.data.id) return { error: "Invalid product." }; const { id, ...data } = parsed.data; await (await products()).updateOne({ id }, { $set: { ...data, inStock: data.stockQty > 0, updatedAt: new Date().toISOString() } }); revalidatePath("/admin/products"); revalidatePath("/shop"); return { success: true }; }
export async function deleteProductAction(id: string) { await requireAdmin(); await (await products()).deleteOne({ id }); revalidatePath("/admin/products"); revalidatePath("/shop"); return { success: true }; }
export async function duplicateProductAction(id: string) { await requireAdmin(); const product = await (await products()).findOne({ id }); if (!product) return { error: "Product not found." }; const copy = { ...product, id: `${product.id}-copy-${Date.now()}`, slug: `${product.slug}-copy-${Date.now()}`, name: `${product.name} Copy`, createdAt: new Date().toISOString() }; delete (copy as { _id?: unknown })._id; await (await products()).insertOne(copy); revalidatePath("/admin/products"); return { success: true }; }
export async function togglePublishedAction(id: string, published: boolean) { await requireAdmin(); await (await products()).updateOne({ id }, { $set: { published, updatedAt: new Date().toISOString() } }); revalidatePath("/admin/products"); revalidatePath("/shop"); return { success: true }; }
