import Link from "next/link";
import { requireSeller } from "@/lib/rbac";
import { products, sellers } from "@/lib/mongodb";
import { deleteSellerProductAction, toggleSellerProductPublishAction } from "@/lib/actions/seller-products";
import { EmptyState, StatusBadge } from "@/components/seller/seller-shell";

async function deleteAction(formData: FormData) { "use server"; await deleteSellerProductAction(String(formData.get("id"))); }
async function toggleAction(formData: FormData) { "use server"; await toggleSellerProductPublishAction(String(formData.get("id")), formData.get("published") !== "true"); }
export default async function SellerProducts({ searchParams }: { searchParams: Promise<{ q?: string }> }) {
  const session = await requireSeller(); const seller = await (await sellers()).findOne({ userId: session.user.id }); const q = (await searchParams).q ?? "";
  const list = seller?._id ? await (await products()).find({ sellerId: seller._id.toString(), ...(q ? { $or: [{ name: { $regex: q, $options: "i" } }, { id: { $regex: q, $options: "i" } }] } : {}) }).sort({ name: 1 }).toArray() : [];
  return <><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="display text-4xl font-semibold">Products / পণ্য</h2><Link href="/seller/products/new" className="bg-foreground px-4 py-3 text-sm text-background">Add product / নতুন পণ্য</Link></div><form className="mt-6 flex gap-2"><input name="q" defaultValue={q} placeholder="Search name or SKU" className="min-h-11 flex-1 border border-border px-3" /><button className="border border-border px-4">Search</button></form><div className="mt-6 overflow-x-auto border border-border"><table className="w-full text-left text-sm"><thead className="bg-muted"><tr>{["SKU / ID","Name","Category","Price","Stock","Status","Actions"].map((x) => <th className="p-3" key={x}>{x}</th>)}</tr></thead><tbody>{list.map((p) => <tr className="border-t border-border" key={p.id}><td className="p-3">{p.id}</td><td className="p-3">{p.name}</td><td className="p-3">{p.category}</td><td className="p-3">৳{p.price.toLocaleString()}</td><td className="p-3">{p.stockQty}</td><td className="p-3"><StatusBadge status={p.published ? "published" : "draft"} /></td><td className="flex gap-2 p-3"><Link href={`/seller/products/${p.id}`} className="underline">Edit</Link><form action={toggleAction}><input type="hidden" name="id" value={p.id} /><input type="hidden" name="published" value={String(Boolean(p.published))} /><button className="underline">{p.published ? "Unpublish" : "Publish"}</button></form><form action={deleteAction}><input type="hidden" name="id" value={p.id} /><button className="text-sale underline">Delete</button></form></td></tr>)}</tbody></table>{!list.length && <EmptyState>No products found / কোনো পণ্য নেই</EmptyState>}</div></>;
}
