import Link from "next/link";
import { notFound } from "next/navigation";
import { Storefront } from "@/components/storefront";
import { technicians } from "@/lib/mongodb";

export default async function TechnicianProfile({ params }: { params: Promise<{ id: string }> }) {
  const tech = await (await technicians()).findOne({ id: (await params).id }); if (!tech) notFound();
  return <Storefront><main className="mx-auto max-w-4xl px-4 py-12 sm:px-6"><div className="grid gap-8 md:grid-cols-[280px_1fr]"><div className="aspect-square bg-muted" /><div><p className="text-xs uppercase tracking-[.2em] text-success">{tech.verified ? "Verified technician" : tech.verificationStatus}</p><h1 className="display mt-3 text-5xl font-semibold">{tech.name}</h1><p className="mt-3 text-foreground/60">{tech.rating} ★ · {tech.completedJobs} completed jobs · {tech.experienceYears} years</p><p className="mt-6 leading-7 text-foreground/70">Experienced HomeFix BD technician serving your home with careful, transparent work.</p><Link href="/booking/new" className="mt-7 inline-flex bg-foreground px-6 py-3 text-sm font-semibold text-background">Book Now</Link></div></div><section className="mt-12 border-t border-border pt-8"><h2 className="display text-3xl font-semibold">Skills & service areas</h2><div className="mt-5 flex flex-wrap gap-2">{tech.skills.map((skill) => <span key={skill.serviceSlug} className="border border-border px-3 py-2 text-sm">{skill.serviceSlug} · {skill.level} · {skill.yearsExperience}y</span>)}</div><p className="mt-5 text-sm text-foreground/60">{tech.serviceAreas.join(" · ")}</p></section><section className="mt-10 border-t border-border pt-8"><h2 className="display text-3xl font-semibold">Availability</h2><div className="mt-5 grid gap-3 sm:grid-cols-3">{(tech.availability ?? []).map((day) => <div key={day.day} className="border border-border p-3 text-sm"><strong>{day.day}</strong><p className="mt-2 text-foreground/60">{day.slots.join(", ")}</p></div>)}</div></section></main></Storefront>;
}
