import Link from "next/link";
import { Storefront } from "@/components/storefront";
import { technicians } from "@/lib/mongodb";
import type { Technician } from "@/types";

export default async function TechniciansPage({ searchParams }: { searchParams: Promise<{ service?: string; area?: string; rating?: string; verified?: string }> }) {
  const filters = await searchParams;
  let list: Technician[] = [];
  try { list = await (await technicians()).find({ active: true }).toArray(); } catch { list = []; }
  list = list.filter((tech) => (!filters.service || tech.skills.some((skill) => skill.serviceSlug === filters.service)) && (!filters.area || tech.serviceAreas.includes(filters.area)) && (!filters.rating || tech.rating >= Number(filters.rating)) && (filters.verified !== "true" || tech.verified));
  return <Storefront><main className="mx-auto max-w-6xl px-4 py-12 sm:px-6"><p className="text-xs uppercase tracking-[.2em] text-sale">Trusted technicians</p><h1 className="display mt-3 text-5xl font-semibold">আপনার কাজের মানুষ</h1><form className="mt-8 grid gap-3 sm:grid-cols-4"><input name="service" placeholder="Service slug" className="border border-border px-3 py-2" /><input name="area" placeholder="Area" className="border border-border px-3 py-2" /><select name="rating" className="border border-border px-3 py-2"><option value="">Any rating</option><option value="4">4+ stars</option><option value="4.5">4.5+ stars</option></select><label className="flex items-center gap-2 border border-border px-3 py-2 text-sm"><input type="checkbox" name="verified" value="true" /> Verified only</label><button className="bg-foreground px-4 py-2 text-sm font-semibold text-background sm:col-span-4">Filter technicians</button></form><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{list.map((tech) => <article key={tech.id} className="border border-border p-5"><div className="aspect-[4/3] bg-muted" /><div className="mt-4 flex items-start justify-between gap-3"><div><h2 className="font-semibold">{tech.name}</h2><p className="mt-1 text-sm text-foreground/60">{tech.rating} ★ · {tech.completedJobs} jobs</p></div>{tech.verified && <span className="text-xs font-semibold text-success">Verified</span>}</div><p className="mt-3 text-sm text-foreground/60">{tech.experienceYears} years experience · Visit ৳{tech.visitCharge}</p><div className="mt-3 flex flex-wrap gap-2">{tech.skills.map((skill) => <span key={skill.serviceSlug} className="bg-muted px-2 py-1 text-xs">{skill.serviceSlug} · {skill.level}</span>)}</div><Link href={`/technicians/${tech.id}`} className="mt-5 inline-flex bg-foreground px-4 py-2 text-sm font-semibold text-background">View profile & book</Link></article>)}</div>{!list.length && <p className="mt-10 border border-border p-8 text-center text-foreground/60">No technicians match these filters.</p>}</main></Storefront>;
}
